import json, os

seeds_dir = 'D:/Development/EducationPlatform/modules/math-algebra/seeds'

# ===== A1.json - 20 questions =====
A1 = [
  {
    "id": "ma-alg-a1-001",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "number-patterns",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.1,
    "prompt": "What comes next: 2, 4, 6, 8, ___?",
    "choices": [{"key": "A", "text": "9"}, {"key": "B", "text": "10"}, {"key": "C", "text": "11"}, {"key": "D", "text": "12"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Almost! This pattern adds 2 each time. 8 + 2 = 10, not 9.", "C": "That's too high. Try adding 2 to 8.", "D": "Close, but we're adding 2 each time, not 4."},
    "explanation": "The pattern is adding 2 each time. So 8 + 2 = 10.",
    "explanationSteps": ["Look at the difference between each number.", "Notice each step adds 2.", "Apply the same rule: 8 + 2 = 10."],
    "hints": ["What number do you add to get from 2 to 4?", "Try the same addition on the last number."],
    "tags": ["patterns", "skip-counting", "addition"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-002",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "number-patterns",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.15,
    "prompt": "What comes next: 5, 10, 15, 20, ___?",
    "choices": [{"key": "A", "text": "22"}, {"key": "B", "text": "25"}, {"key": "C", "text": "30"}, {"key": "D", "text": "35"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Not quite. This pattern adds 5 each time. 20 + 5 = 25.", "C": "That's too many. We add 5, not 10.", "D": "A bit too high. Try adding 5 to 20."},
    "explanation": "Each number increases by 5. So 20 + 5 = 25.",
    "explanationSteps": ["Find the difference: 10 - 5 = 5.", "Check the next pair: 15 - 10 = 5.", "Add 5 to the last number: 20 + 5 = 25."],
    "hints": ["How much is added from 5 to 10?", "Add that same amount to 20."],
    "tags": ["patterns", "skip-counting", "multiplication"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-003",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "number-patterns",
    "level": "A1",
    "questionType": "gap-filling",
    "difficulty": 0.2,
    "prompt": "Fill in the missing number: 3, 6, ___, 12, 15",
    "choices": [{"key": "A", "text": "7"}, {"key": "B", "text": "8"}, {"key": "C", "text": "9"}, {"key": "D", "text": "10"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "Not quite. The pattern adds 3 each time. 6 + 3 = 9.", "B": "Almost! Try counting up by 3s: 3, 6, 9, 12.", "D": "Close, but the step is 3, not 4."},
    "explanation": "The pattern adds 3 each time. The missing number is 9.",
    "explanationSteps": ["Check the difference between known numbers.", "The rule is add 3.", "Apply it: 6 + 3 = 9."],
    "hints": ["What is the difference between 3 and 6?", "Use that same difference after 6."],
    "tags": ["patterns", "missing-term", "addition"], "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a1-004",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "number-patterns",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.15,
    "prompt": "What number comes next: 1, 4, 7, 10, ___?",
    "choices": [{"key": "A", "text": "11"}, {"key": "B", "text": "12"}, {"key": "C", "text": "13"}, {"key": "D", "text": "14"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "Almost! Add 3 to 10, not 1.", "B": "That's adding 2. Try adding 3 instead.", "D": "A bit high. The pattern adds 3, so 10 + 3 = 13."},
    "explanation": "The pattern adds 3 each time. So 10 + 3 = 13.",
    "explanationSteps": ["Find the step: 4 - 1 = 3.", "Check: 7 - 4 = 3.", "Add 3 to 10: 10 + 3 = 13."],
    "hints": ["What is 4 minus 1?", "Add that number to 10."],
    "tags": ["patterns", "skip-counting", "addition"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-005",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "shape-patterns",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.2,
    "prompt": "Look at this shape pattern: circle, square, triangle, circle, square, ___? What comes next?",
    "choices": [{"key": "A", "text": "circle"}, {"key": "B", "text": "square"}, {"key": "C", "text": "triangle"}, {"key": "D", "text": "star"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "The pattern repeats every 3 shapes. After square comes triangle.", "B": "Look carefully at the repeating cycle.", "D": "Star is not part of this repeating pattern."},
    "explanation": "The shapes repeat in a cycle of 3: circle, square, triangle.",
    "explanationSteps": ["Notice the shapes repeat in the same order.", "The cycle length is 3 shapes.", "After square comes triangle."],
    "hints": ["How many different shapes are in the pattern?", "What comes after square in the first set?"],
    "tags": ["patterns", "shapes", "cycles"], "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a1-006",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "number-patterns",
    "level": "A1",
    "questionType": "gap-filling",
    "difficulty": 0.25,
    "prompt": "Fill in the missing number: 20, 16, 12, ___, 4",
    "choices": [{"key": "A", "text": "10"}, {"key": "B", "text": "8"}, {"key": "C", "text": "6"}, {"key": "D", "text": "0"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Almost! We subtract 4 each time. 12 - 4 = 8.", "C": "Close! The step is 4, not 6.", "D": "That's subtracting too much."},
    "explanation": "This is a decreasing pattern subtracting 4 each time. The missing number is 8.",
    "explanationSteps": ["Find how much is subtracted: 20 - 16 = 4.", "Check: 16 - 12 = 4.", "Subtract 4 from 12: 12 - 4 = 8."],
    "hints": ["What is 20 minus 16?", "Subtract that number from 12."],
    "tags": ["patterns", "decreasing", "subtraction"], "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a1-007",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "number-patterns",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.2,
    "prompt": "What comes next: 10, 20, 30, 40, ___?",
    "choices": [{"key": "A", "text": "45"}, {"key": "B", "text": "50"}, {"key": "C", "text": "60"}, {"key": "D", "text": "100"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Almost! We add 10 each time. 40 + 10 = 50.", "C": "That's adding 20.", "D": "That jumps too far ahead."},
    "explanation": "This pattern adds 10 each time. So 40 + 10 = 50.",
    "explanationSteps": ["Find the difference: 20 - 10 = 10.", "Check it's the same.", "Add 10 to 40."],
    "hints": ["What is 20 minus 10?", "Add that to 40."],
    "tags": ["patterns", "skip-counting", "tens"], "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a1-008",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "arithmetic-sequences",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.3,
    "prompt": "What is the next number: 1, 3, 5, 7, ___?",
    "choices": [{"key": "A", "text": "8"}, {"key": "B", "text": "9"}, {"key": "C", "text": "10"}, {"key": "D", "text": "11"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Almost! We add 2 each time. 7 + 2 = 9.", "C": "That's adding 3.", "D": "A bit too high."},
    "explanation": "Each term adds 2. So 7 + 2 = 9.",
    "explanationSteps": ["Find difference: 3 - 1 = 2.", "Confirm: 5 - 3 = 2.", "Add 2 to 7."],
    "hints": ["What do you add to 1 to get 3?", "Add that number to 7."],
    "tags": ["sequences", "odd-numbers", "arithmetic"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-009",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "shape-patterns",
    "level": "A1",
    "questionType": "gap-filling",
    "difficulty": 0.3,
    "prompt": "Complete the pattern: a, bb, ccc, ____, eeeee",
    "choices": [{"key": "A", "text": "dd"}, {"key": "B", "text": "dddd"}, {"key": "C", "text": "dddddd"}, {"key": "D", "text": "ddd"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That would be 2 letters. We need 4.", "C": "That's 6 letters. Pattern increases by 1.", "D": "There are already 3 at position 3."},
    "explanation": "The number of letters increases by 1 each time. The missing entry has 4 d's.",
    "explanationSteps": ["Count the letters: 1, 2, 3, ?, 5.", "The missing number is 4."],
    "hints": ["How many letters are in each group?", "How many should come between 3 and 5?"],
    "tags": ["patterns", "visual", "counting"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-010",
    "moduleId": "math.algebra",
    "skill": "patterns-sequences",
    "subSkill": "arithmetic-sequences",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.35,
    "prompt": "What is the 6th number in this sequence: 2, 4, 6, 8, ...?",
    "choices": [{"key": "A", "text": "10"}, {"key": "B", "text": "11"}, {"key": "C", "text": "12"}, {"key": "D", "text": "14"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "That's the 5th term.", "B": "This sequence has only even numbers.", "D": "That's too far."},
    "explanation": "The sequence is 2, 4, 6, 8, 10, 12. The 6th term is 12 = 2 x 6.",
    "explanationSteps": ["List: 2, 4, 6, 8, 10, 12.", "Each term adds 2.", "The 6th term = 2 x 6 = 12."],
    "hints": ["Can you write out the first 6 numbers?", "What is 2 x 6?"],
    "tags": ["sequences", "even-numbers", "arithmetic"], "estimatedTimeSec": 40
  },
  {
    "id": "ma-alg-a1-011",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "variable-concepts",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.15,
    "prompt": "If a = 5, what is a + 3?",
    "choices": [{"key": "A", "text": "5"}, {"key": "B", "text": "8"}, {"key": "C", "text": "10"}, {"key": "D", "text": "15"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Replace 'a' with 5, then 5 + 3 = 8.", "C": "That would be a + 5.", "D": "That's a x 3."},
    "explanation": "The variable a stands for 5. a + 3 = 5 + 3 = 8.",
    "explanationSteps": ["Identify what a represents: a = 5.", "Substitute: 5 + 3.", "Add: 5 + 3 = 8."],
    "hints": ["What number does 'a' stand for?", "Add 3 to that number."],
    "tags": ["variables", "substitution", "addition"], "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a1-012",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "variable-concepts",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.2,
    "prompt": "If b = 7, what is b - 2?",
    "choices": [{"key": "A", "text": "5"}, {"key": "B", "text": "7"}, {"key": "C", "text": "9"}, {"key": "D", "text": "14"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "We need to subtract 2 from b.", "C": "That would be b + 2.", "D": "That's b x 2."},
    "explanation": "b - 2 = 7 - 2 = 5.",
    "explanationSteps": ["Identify: b = 7.", "Substitute: 7 - 2.", "Subtract: 7 - 2 = 5."],
    "hints": ["What number does 'b' stand for?", "Subtract 2 from that number."],
    "tags": ["variables", "substitution", "subtraction"], "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a1-013",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "variable-concepts",
    "level": "A1",
    "questionType": "gap-filling",
    "difficulty": 0.25,
    "prompt": "If n = 4, what is 3 x n?",
    "choices": [{"key": "A", "text": "7"}, {"key": "B", "text": "12"}, {"key": "C", "text": "34"}, {"key": "D", "text": "81"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That's 3 + n, not 3 x n.", "C": "That looks like you put 3 and 4 next to each other.", "D": "That's 3 to the power of 4."},
    "explanation": "3 x n = 3 x 4 = 12.",
    "explanationSteps": ["Identify: n = 4.", "Replace n: 3 x 4.", "Multiply: 3 x 4 = 12."],
    "hints": ["n equals what number?", "What is 3 groups of that number?"],
    "tags": ["variables", "substitution", "multiplication"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-014",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "writing-expressions",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.3,
    "prompt": "Which expression means 'a number plus 5' using x for the number?",
    "choices": [{"key": "A", "text": "5 - x"}, {"key": "B", "text": "x + 5"}, {"key": "C", "text": "x x 5"}, {"key": "D", "text": "5 / x"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "5 - x means '5 minus a number'.", "C": "x x 5 means 'a number times 5'.", "D": "5 / x means '5 divided by a number'."},
    "explanation": "When we say 'a number plus 5' and use x for the number, we write x + 5.",
    "explanationSteps": ["Let x be the unknown number.", "Plus 5 means add 5 to x.", "The expression is x + 5."],
    "hints": ["What letter stands for 'a number'?", "What operation does 'plus' mean?"],
    "tags": ["variables", "writing-expressions", "translation"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-015",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "writing-expressions",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.35,
    "prompt": "Which expression means 'twice a number' using y for the number?",
    "choices": [{"key": "A", "text": "y + 2"}, {"key": "B", "text": "y - 2"}, {"key": "C", "text": "2 / y"}, {"key": "D", "text": "2 x y"}],
    "answerKey": "D",
    "wrongChoiceReasons": {"A": "y + 2 means 'a number plus 2'.", "B": "y - 2 means 'a number minus 2'.", "C": "2 / y means '2 divided by a number'."},
    "explanation": "'Twice a number' means multiply by 2. So 2 x y.",
    "explanationSteps": ["Let y be the unknown number.", "Twice means 2 times.", "The expression is 2 x y."],
    "hints": ["What does 'twice' mean?", "What operation is 'times'?"],
    "tags": ["variables", "writing-expressions", "multiplication"], "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a1-016",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A1",
    "questionType": "gap-filling",
    "difficulty": 0.3,
    "prompt": "If c = 3, what is 2 x c + 1?",
    "choices": [{"key": "A", "text": "5"}, {"key": "B", "text": "6"}, {"key": "C", "text": "7"}, {"key": "D", "text": "9"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "Multiply first: 2 x 3 = 6, then 6 + 1 = 7.", "B": "Don't forget to add 1.", "D": "Multiply first."},
    "explanation": "2 x c + 1 = 2 x 3 + 1 = 6 + 1 = 7.",
    "explanationSteps": ["Identify: c = 3.", "Substitute: 2 x 3 + 1.", "Multiply first: 6 + 1 = 7."],
    "hints": ["First find 2 x c. What is 2 x 3?", "Then add 1."],
    "tags": ["variables", "evaluation", "order-of-operations"], "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a1-017",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "writing-expressions",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.35,
    "prompt": "There are p apples. Sarah takes 3. Which expression shows apples left?",
    "choices": [{"key": "A", "text": "p + 3"}, {"key": "B", "text": "3 - p"}, {"key": "C", "text": "p - 3"}, {"key": "D", "text": "p / 3"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "p + 3 means adding apples.", "B": "3 - p would mean 3 minus apples.", "D": "Division doesn't make sense here."},
    "explanation": "Start with p apples. Take 3 away: p - 3.",
    "explanationSteps": ["Start with p apples.", "Takes 3 away (subtract).", "Remaining = p - 3."],
    "hints": ["Does 'takes' mean add or subtract?", "Start with p, then what?"],
    "tags": ["variables", "writing-expressions", "word-problems"], "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a1-018",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A1",
    "questionType": "gap-filling",
    "difficulty": 0.35,
    "prompt": "If d = 6, what is d / 2 + 4?",
    "choices": [{"key": "A", "text": "3"}, {"key": "B", "text": "5"}, {"key": "C", "text": "7"}, {"key": "D", "text": "10"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "You found d / 2, but add 4.", "B": "Almost! 6 / 2 = 3, then 3 + 4 = 7.", "D": "Divide first."},
    "explanation": "d / 2 + 4 = 6 / 2 + 4 = 3 + 4 = 7.",
    "explanationSteps": ["Identify: d = 6.", "Substitute: 6 / 2 + 4.", "Divide first: 3 + 4 = 7."],
    "hints": ["First find d / 2. What is 6 / 2?", "Then add 4."],
    "tags": ["variables", "evaluation", "order-of-operations"], "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a1-019",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.4,
    "prompt": "If x = 2, what is 3 x x + x?",
    "choices": [{"key": "A", "text": "6"}, {"key": "B", "text": "8"}, {"key": "C", "text": "10"}, {"key": "D", "text": "12"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That's just 3 x x. Add x too.", "C": "Check: 3 x 2 = 6, 6 + 2 = 8.", "D": "That's 3 x 2 x 2."},
    "explanation": "3 x x + x = 3 x 2 + 2 = 6 + 2 = 8.",
    "explanationSteps": ["Identify: x = 2.", "Substitute: 3 x 2 + 2.", "Multiply first: 6 + 2 = 8."],
    "hints": ["What is 3 x 2?", "Now add x again. What is x?"],
    "tags": ["variables", "evaluation", "multiple-occurrences"], "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a1-020",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "variable-concepts",
    "level": "A1",
    "questionType": "multiple-choice",
    "difficulty": 0.3,
    "prompt": "If m = 9 and n = 2, what is m - n?",
    "choices": [{"key": "A", "text": "7"}, {"key": "B", "text": "11"}, {"key": "C", "text": "18"}, {"key": "D", "text": "92"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "That would be m + n.", "C": "That's m x n.", "D": "That's writing numbers side by side."},
    "explanation": "m - n = 9 - 2 = 7.",
    "explanationSteps": ["Identify: m = 9, n = 2.", "Substitute: 9 - 2.", "Subtract: 9 - 2 = 7."],
    "hints": ["What does m stand for? n?", "Subtract n from m."],
    "tags": ["variables", "substitution", "two-variables"], "estimatedTimeSec": 30
  }
]

with open(os.path.join(seeds_dir, 'A1.json'), 'w', encoding='utf-8') as f:
    json.dump(A1, f, indent=2, ensure_ascii=False)
print('A1.json written with', len(A1), 'questions')
import json, os

seeds_dir = 'D:/Development/EducationPlatform/modules/math-algebra/seeds'
os.makedirs(seeds_dir, exist_ok=True)

A2 = [
  {
    "id": "ma-alg-a2-001",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.25,
    "prompt": "If x = 4, what is 3x + 5?",
    "choices": [{"key": "A", "text": "12"}, {"key": "B", "text": "17"}, {"key": "C", "text": "20"}, {"key": "D", "text": "27"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That's only 3x. Don't forget to add 5.", "C": "Check your multiplication. 3 x 4 = 12, then 12 + 5 = 17.", "D": "That looks like 3 x (4 + 5). Remember the order: multiply first."},
    "explanation": "3x means 3 x x. With x = 4: 3(4) + 5 = 12 + 5 = 17.",
    "explanationSteps": ["Replace x with 4: 3(4) + 5.", "Multiply: 3 x 4 = 12.", "Add: 12 + 5 = 17."],
    "hints": ["What does 3x mean?", "What is 3 times 4?", "Now add 5."],
    "tags": ["variables", "evaluation", "multiplication"],
    "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a2-002",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.3,
    "prompt": "If y = 10, what is 2y - 3?",
    "choices": [{"key": "A", "text": "7"}, {"key": "B", "text": "14"}, {"key": "C", "text": "17"}, {"key": "D", "text": "20"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "You subtracted 3 from 10, but remember 2y means 2 x y first.", "B": "That's 2y, but don't forget to subtract 3.", "D": "That is just y + 10. Compute 2 x 10 - 3 = 20 - 3 = 17."},
    "explanation": "Replace y with 10: 2(10) - 3 = 20 - 3 = 17.",
    "explanationSteps": ["Substitute y = 10: 2 x 10 - 3.", "Multiply: 20 - 3.", "Subtract: 17."],
    "hints": ["What is 2 x 10?", "Now subtract 3 from that."],
    "tags": ["variables", "evaluation", "subtraction"],
    "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a2-003",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "writing-expressions",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.3,
    "prompt": "Which expression represents '6 more than twice a number n'?",
    "choices": [{"key": "A", "text": "2n + 6"}, {"key": "B", "text": "6n + 2"}, {"key": "C", "text": "2(n + 6)"}, {"key": "D", "text": "n + 6 + 2"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "This means '2 more than 6 times n', not '6 more than twice n'.", "C": "This means 'twice the sum of n and 6', which is different.", "D": "This just means n + 8. We need twice n first, then add 6."},
    "explanation": "'Twice a number n' is 2n. '6 more than' means add 6. Together: 2n + 6.",
    "explanationSteps": ["'Twice a number n' means 2 x n = 2n.", "'6 more than' means add 6.", "Combine: 2n + 6."],
    "hints": ["What does 'twice a number' mean?", "What operation does 'more than' tell you to use?"],
    "tags": ["variables", "writing-expressions", "translation"],
    "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a2-004",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "like-terms",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.35,
    "prompt": "Simplify: 3x + 2x",
    "choices": [{"key": "A", "text": "5x"}, {"key": "B", "text": "6x"}, {"key": "C", "text": "5x2"}, {"key": "D", "text": "x + 5"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "3x + 2x = 5x, not 6x. Check your addition.", "C": "The x doesn't become squared. We just add the coefficients: 3 + 2 = 5.", "D": "We keep the variable x. 3x + 2x = (3 + 2)x = 5x."},
    "explanation": "Both terms have the same variable x. Add the coefficients: 3 + 2 = 5, so 3x + 2x = 5x.",
    "explanationSteps": ["Identify like terms: both have x.", "Add coefficients: 3 + 2 = 5.", "Keep the variable: 5x."],
    "hints": ["What do 3x and 2x have in common?", "Add the numbers in front of x."],
    "tags": ["like-terms", "simplification", "coefficients"],
    "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a2-005",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "like-terms",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.4,
    "prompt": "Simplify: 4a + 3b + 2a + b",
    "choices": [{"key": "A", "text": "6a + 4b"}, {"key": "B", "text": "6a + 3b"}, {"key": "C", "text": "4a + 6b"}, {"key": "D", "text": "10ab"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "Check the b terms: 3b + b = 3b + 1b = 4b, not 3b.", "C": "Check the a terms: 4a + 2a = 6a, not 4a.", "D": "a and b are different variables. You can't combine them into ab."},
    "explanation": "Group a terms: 4a + 2a = 6a. Group b terms: 3b + b = 4b. Result: 6a + 4b.",
    "explanationSteps": ["Group like terms: (4a + 2a) + (3b + b).", "Add a coefficients: 4 + 2 = 6a.", "Add b coefficients: 3 + 1 = 4b.", "Combine: 6a + 4b."],
    "hints": ["Which terms have 'a'? Add those together.", "Which terms have 'b'? Add those together.", "Remember that b is the same as 1b."],
    "tags": ["like-terms", "simplification", "multiple-variables"],
    "estimatedTimeSec": 40
  },
  {
    "id": "ma-alg-a2-006",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.35,
    "prompt": "Evaluate 4(x + 3) when x = 5.",
    "choices": [{"key": "A", "text": "23"}, {"key": "B", "text": "32"}, {"key": "C", "text": "20"}, {"key": "D", "text": "17"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "Check your arithmetic. 4 x (5 + 3) = 4 x 8, not 4 x 5 + 3.", "C": "Add inside the parentheses first: 5 + 3 = 8, then 4 x 8 = 32.", "D": "You may have done 4 x 5 - 3. Try 4(5 + 3) = 4 x 8 = 32."},
    "explanation": "Substitute x = 5: 4(5 + 3) = 4 x 8 = 32.",
    "explanationSteps": ["Substitute x = 5: 4(5 + 3).", "Add inside parentheses: 5 + 3 = 8.", "Multiply: 4 x 8 = 32."],
    "hints": ["What is inside the parentheses first?", "Add before multiplying."],
    "tags": ["variables", "evaluation", "parentheses"],
    "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a2-007",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "writing-expressions",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.4,
    "prompt": "A rectangle has length L and width 5. Which expression represents its perimeter?",
    "choices": [{"key": "A", "text": "L + 5"}, {"key": "B", "text": "L x 5"}, {"key": "C", "text": "2L + 10"}, {"key": "D", "text": "2L + 5"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "That's just one side plus width. Perimeter is the sum of all sides.", "B": "That is area, not perimeter. Perimeter = 2 x length + 2 x width.", "D": "Almost! Width is 5, so both widths together = 2 x 5 = 10."},
    "explanation": "Perimeter = 2 x length + 2 x width = 2L + 2(5) = 2L + 10.",
    "explanationSteps": ["Perimeter formula: P = 2L + 2W.", "Width is 5, so 2 x 5 = 10.", "Expression: 2L + 10."],
    "hints": ["How many sides does a rectangle have?", "What is the formula for perimeter?"],
    "tags": ["variables", "writing-expressions", "geometry"],
    "estimatedTimeSec": 40
  },
  {
    "id": "ma-alg-a2-008",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "like-terms",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.45,
    "prompt": "Simplify: 5x + 3 - 2x + 7",
    "choices": [{"key": "A", "text": "3x + 10"}, {"key": "B", "text": "7x + 10"}, {"key": "C", "text": "3x + 4"}, {"key": "D", "text": "7x + 4"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "Check the x terms: 5x - 2x = 3x, not 7x.", "C": "Check the constants: 3 + 7 = 10, not 4.", "D": "Both terms are wrong. 5x - 2x = 3x and 3 + 7 = 10."},
    "explanation": "Group x terms: 5x - 2x = 3x. Group constants: 3 + 7 = 10. Result: 3x + 10.",
    "explanationSteps": ["Group x terms: 5x - 2x.", "Subtract coefficients: 5 - 2 = 3x.", "Group constants: 3 + 7 = 10.", "Combine: 3x + 10."],
    "hints": ["Combine the x terms first: 5x - 2x.", "Then combine the plain numbers: 3 + 7."],
    "tags": ["like-terms", "simplification", "constants"],
    "estimatedTimeSec": 40
  },
  {
    "id": "ma-alg-a2-009",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "evaluating-expressions",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.4,
    "prompt": "If a = 3 and b = 4, what is a2 + b?",
    "choices": [{"key": "A", "text": "9"}, {"key": "B", "text": "13"}, {"key": "C", "text": "16"}, {"key": "D", "text": "25"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That's just a2. Don't forget to add b = 4.", "C": "That is b2. We need a2 + b = 32 + 4 = 9 + 4 = 13.", "D": "That is (a + b)2. Here we square only a, then add b."},
    "explanation": "a2 means 32 = 9. Then add b = 4. So 9 + 4 = 13.",
    "explanationSteps": ["Substitute: a2 + b = 32 + 4.", "Square: 32 = 9.", "Add: 9 + 4 = 13."],
    "hints": ["What is 3 squared?", "Then add 4."],
    "tags": ["variables", "evaluation", "exponents"],
    "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a2-010",
    "moduleId": "math.algebra",
    "skill": "variables-expressions",
    "subSkill": "writing-expressions",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.45,
    "prompt": "A number n is divided by 3, then 2 is added. Which expression represents this?",
    "choices": [{"key": "A", "text": "3 / n + 2"}, {"key": "B", "text": "n / 3 + 2"}, {"key": "C", "text": "n / (3 + 2)"}, {"key": "D", "text": "3 / (n + 2)"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That's '3 divided by n', not 'n divided by 3'.", "C": "This divides n by 5, but we divide by 3 first, then add 2.", "D": "This is 3 divided by (n + 2), which is different."},
    "explanation": "Start with n, divide by 3 gives n / 3, then add 2 gives n / 3 + 2.",
    "explanationSteps": ["Start with n.", "Divide by 3: n / 3.", "Then add 2: n / 3 + 2."],
    "hints": ["What operation does 'divided by' mean?", "What comes first: division or addition?"],
    "tags": ["variables", "writing-expressions", "order-of-operations"],
    "estimatedTimeSec": 40
  },
  {
    "id": "ma-alg-a2-011",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "one-step-equations",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.25,
    "prompt": "Solve: x + 7 = 15",
    "choices": [{"key": "A", "text": "7"}, {"key": "B", "text": "8"}, {"key": "C", "text": "15"}, {"key": "D", "text": "22"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "If x were 7, then 7 + 7 = 14, not 15.", "C": "That's the right side. x is what we add to 7 to get 15.", "D": "That's 7 + 15. To solve, subtract 7 from both sides."},
    "explanation": "Subtract 7 from both sides: x + 7 - 7 = 15 - 7, so x = 8.",
    "explanationSteps": ["x + 7 = 15.", "Subtract 7 from both sides: x = 15 - 7.", "x = 8."],
    "hints": ["What number added to 7 equals 15?", "Try subtracting 7 from 15."],
    "tags": ["equations", "one-step", "addition"],
    "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a2-012",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "one-step-equations",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.25,
    "prompt": "Solve: y - 5 = 9",
    "choices": [{"key": "A", "text": "4"}, {"key": "B", "text": "9"}, {"key": "C", "text": "14"}, {"key": "D", "text": "45"}],
    "answerKey": "C",
    "wrongChoiceReasons": {"A": "If y = 4, then 4 - 5 = -1, not 9. We need to add 5 to both sides.", "B": "That's the right side. y - 5 = 9, so y is bigger than 9.", "D": "That's 9 x 5. We need to add 5 to both sides: y = 9 + 5 = 14."},
    "explanation": "Add 5 to both sides: y - 5 + 5 = 9 + 5, so y = 14.",
    "explanationSteps": ["y - 5 = 9.", "Add 5 to both sides: y = 9 + 5.", "y = 14."],
    "hints": ["What number minus 5 equals 9?", "Try adding 5 to 9."],
    "tags": ["equations", "one-step", "subtraction"],
    "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a2-013",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "one-step-equations",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.3,
    "prompt": "Solve: 3a = 18",
    "choices": [{"key": "A", "text": "6"}, {"key": "B", "text": "15"}, {"key": "C", "text": "21"}, {"key": "D", "text": "54"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "If a = 15, then 3 x 15 = 45, not 18. Divide 18 by 3.", "C": "That's 3 + 18. To solve 3a = 18, divide both sides by 3.", "D": "That's 3 x 18. We need to find what number times 3 equals 18."},
    "explanation": "Divide both sides by 3: 3a / 3 = 18 / 3, so a = 6.",
    "explanationSteps": ["3a = 18.", "Divide both sides by 3: a = 18 / 3.", "a = 6."],
    "hints": ["What number times 3 equals 18?", "Try dividing 18 by 3."],
    "tags": ["equations", "one-step", "multiplication"],
    "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a2-014",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "one-step-equations",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.3,
    "prompt": "Solve: b / 4 = 5",
    "choices": [{"key": "A", "text": "9"}, {"key": "B", "text": "20"}, {"key": "C", "text": "1.25"}, {"key": "D", "text": "0.8"}],
    "answerKey": "B",
    "wrongChoiceReasons": {"A": "That's 4 + 5. To undo division by 4, multiply both sides by 4.", "C": "That's 5 / 4. We need b = 5 x 4 = 20.", "D": "That's 4 / 5. Multiply 5 by 4 to find b."},
    "explanation": "Multiply both sides by 4: (b / 4) x 4 = 5 x 4, so b = 20.",
    "explanationSteps": ["b / 4 = 5.", "Multiply both sides by 4: b = 5 x 4.", "b = 20."],
    "hints": ["If b divided by 4 gives 5, what is b?", "Try multiplying 5 by 4."],
    "tags": ["equations", "one-step", "division"],
    "estimatedTimeSec": 25
  },
  {
    "id": "ma-alg-a2-015",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "inequalities",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.35,
    "prompt": "Which of these numbers is a solution to x > 4?",
    "choices": [{"key": "A", "text": "2"}, {"key": "B", "text": "3"}, {"key": "C", "text": "4"}, {"key": "D", "text": "5"}],
    "answerKey": "D",
    "wrongChoiceReasons": {"A": "2 is less than 4, and we need numbers greater than 4.", "B": "3 is less than 4. Look for a number bigger than 4.", "C": "x > 4 means strictly greater than 4. 4 is not included."},
    "explanation": "x > 4 means x is any number greater than 4. Among the choices, only 5 > 4.",
    "explanationSteps": ["x > 4 means 'x is greater than 4'.", "Check each option: 2 < 4, 3 < 4, 4 = 4 (not >), 5 > 4.", "Only 5 satisfies the inequality."],
    "hints": ["What does the symbol > mean?", "Which numbers are bigger than 4?"],
    "tags": ["inequalities", "comparison", "solutions"],
    "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a2-016",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "two-step-equations",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.4,
    "prompt": "Solve: 2x + 3 = 11",
    "choices": [{"key": "A", "text": "4"}, {"key": "B", "text": "5"}, {"key": "C", "text": "7"}, {"key": "D", "text": "8"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "Check: 2(5) + 3 = 13, not 11. Subtract 3 first, then divide by 2.", "C": "That's 11 - 4. Try: 2x = 11 - 3, so 2x = 8, then x = 4.", "D": "Check: 2(8) + 3 = 19. Subtract 3 then divide by 2."},
    "explanation": "Subtract 3 from both sides: 2x = 8. Then divide by 2: x = 4.",
    "explanationSteps": ["2x + 3 = 11.", "Subtract 3: 2x = 8.", "Divide by 2: x = 4."],
    "hints": ["First undo the +3. What is 11 - 3?", "Then undo the multiplication by 2."],
    "tags": ["equations", "two-step", "inverse-operations"],
    "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a2-017",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "inequalities",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.4,
    "prompt": "Solve: x + 3 <= 7",
    "choices": [{"key": "A", "text": "x <= 4"}, {"key": "B", "text": "x <= 10"}, {"key": "C", "text": "x >= 4"}, {"key": "D", "text": "x >= 10"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "That would be from adding, not subtracting. Subtract 3 from both sides.", "C": "The inequality sign stays the same when subtracting. x <= 4, not x >= 4.", "D": "Both the number and direction are wrong. Subtract 3 from both sides."},
    "explanation": "Subtract 3 from both sides: x + 3 - 3 <= 7 - 3, so x <= 4.",
    "explanationSteps": ["x + 3 <= 7.", "Subtract 3 from both sides: x <= 7 - 3.", "x <= 4."],
    "hints": ["What operation undoes +3?", "Remember to do the same to both sides."],
    "tags": ["inequalities", "one-step", "less-than-or-equal"],
    "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a2-018",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "two-step-equations",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.45,
    "prompt": "Solve: 5x - 4 = 16",
    "choices": [{"key": "A", "text": "4"}, {"key": "B", "text": "5"}, {"key": "C", "text": "12"}, {"key": "D", "text": "20"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "Check: 5(5) - 4 = 21, not 16. Add 4 first, then divide by 5.", "C": "That's 16 - 4. First add 4: 5x = 20, then divide: x = 4.", "D": "That's 5x. Divide by 5 to get x = 4."},
    "explanation": "Add 4 to both sides: 5x = 20. Then divide by 5: x = 4.",
    "explanationSteps": ["5x - 4 = 16.", "Add 4: 5x = 20.", "Divide by 5: x = 4."],
    "hints": ["First undo the -4. Add 4 to both sides.", "Then undo the x5. Divide both sides by 5."],
    "tags": ["equations", "two-step", "inverse-operations"],
    "estimatedTimeSec": 35
  },
  {
    "id": "ma-alg-a2-019",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "inequalities",
    "level": "A2",
    "questionType": "gap-filling",
    "difficulty": 0.45,
    "prompt": "Solve: 2x > 10",
    "choices": [{"key": "A", "text": "x > 5"}, {"key": "B", "text": "x > 8"}, {"key": "C", "text": "x > 12"}, {"key": "D", "text": "x > 20"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "Check: 2 x 8 = 16, which is more than 10, but the boundary is 10 / 2 = 5.", "C": "That's 10 + 2. We need to divide both sides by 2.", "D": "That's 10 x 2. Divide both sides by 2 to solve."},
    "explanation": "Divide both sides by 2: 2x / 2 > 10 / 2, so x > 5.",
    "explanationSteps": ["2x > 10.", "Divide both sides by 2: x > 10 / 2.", "x > 5."],
    "hints": ["What operation undoes multiplication by 2?", "Apply the same operation to both sides."],
    "tags": ["inequalities", "one-step", "multiplication"],
    "estimatedTimeSec": 30
  },
  {
    "id": "ma-alg-a2-020",
    "moduleId": "math.algebra",
    "skill": "equations-inequalities",
    "subSkill": "two-step-equations",
    "level": "A2",
    "questionType": "multiple-choice",
    "difficulty": 0.5,
    "prompt": "Solve: 3(x + 2) = 18",
    "choices": [{"key": "A", "text": "4"}, {"key": "B", "text": "5"}, {"key": "C", "text": "6"}, {"key": "D", "text": "16"}],
    "answerKey": "A",
    "wrongChoiceReasons": {"B": "Check: 3(5 + 2) = 21, not 18. Either divide by 3 first, or distribute.", "C": "If x = 6, then 3(6 + 2) = 24. Try dividing 18 by 3 first.", "D": "That's 18 - 2. First divide both sides by 3, then subtract 2."},
    "explanation": "Divide both sides by 3: x + 2 = 6. Then subtract 2: x = 4.",
    "explanationSteps": ["3(x + 2) = 18.", "Divide by 3: x + 2 = 6.", "Subtract 2: x = 4."],
    "hints": ["First undo the x3. Divide 18 by 3.", "Then undo the +2."],
    "tags": ["equations", "two-step", "parentheses"],
    "estimatedTimeSec": 40
  }
]

with open(os.path.join(seeds_dir, 'A2.json'), 'w', encoding='utf-8') as f:
    json.dump(A2, f, indent=2, ensure_ascii=False)
print('A2.json written with', len(A2), 'questions')
